 query ListAdverts{
      allAdvert {
        _id
        contact
        description
        _type
        title
        subcategory {
          _id
          name
        }
        location
        price
        image {
          asset {
            url
          }
        }
      }
    }