 query ListAdverts{
      allAdvert {
        _id
        user{
          _id
          _type
          _createdAt
          _updatedAt
  name
  email
  image
}
        slug{
          current
        }
        contact
        description
        _type
        title
        subcategory {
          _id
          name
           category{
          _id,
          slug{
            current
          }
          name
        }
        }
        location{
          lat
          lng
          alt
         
        }
       
        price
        image {
          asset {
            url
          }
        }
      }
    }

query GetAdvert ($id: ID!){
		Advert(id:$id) {

_id
user{
          _id
          _type
          _createdAt
          _updatedAt
  name
  email
  image
}
 slug{
          current
        }
        contact
        description
        _type
        title
        subcategory {
          _id
          name
        }
        location{
          lat
          lng
          alt
         
        }
        price
        image {
          asset {
            url
          }
        }
        }
        }


query ListAdvertsByCategory($slug:String!){allAdvert(where :{subcategory :{category :{slug: {current: {eq: $slug}} }}})
{_id,title,_createdAt,slug{current},description,subcategory{_id,name,slug{current}},contact,price,location{lat,lng,alt},image{asset{url}}}
}

query ListAdvertsBySubCategory($slug:String!){allAdvert(where :{subcategory :{slug:{current : {eq: $slug}}}})
{_id,title,_createdAt,slug{current},description,subcategory{_id,name,slug{current}},contact,price,location{lat,lng,alt},image{asset{url}}}
}

query ListAdvertSearch($lat:Float!,$lng:Float,$title:String!,$subcategory: ID!){allAdvert(where:{location :{lat:{eq:$lat},lng:{eq:$lng}},
title:{matches:$title}, subcategory:{_id:{eq:$subcategory}}})
{_id,title,_createdAt,slug{current},description,subcategory{_id,name,slug{current}},contact,price,location{lat,lng,alt},image{asset{url}}}
}