	query GetPosts{
		allPost {
			title
			slug {
				current
			}
			contentRaw
			excerpt
			coverImage {
				asset {
					url
					originalFilename
					source{
						id
						url
					}
					path
					uploadId
					assetId
					size
					mimeType
					extension
					sha1hash
				}
			}
			date
			author{
				name
				picture {
					asset {
						url
						originalFilename
						source{
							id
							url
						}
						path
						uploadId
						assetId
						size
						mimeType
						extension
						sha1hash
					}
				}
			}
		}
	}